name: 'sado_analytics_services'
version: '1.0.0'
config-version: 2

require-dbt-version: ">=1.6.0"
profile: 'sado_analytics_services'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"

models:
  sado_analytics_services:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
      +docs:
        show: false
    marts:
      +materialized: table
      sales:
        +schema: sales
      dimensions:
        +schema: dimensions
      marketing:
        +schema: marketing
      online_sales:
        +schema: online_sales
    utilities:
      +materialized: view
      +docs:
        show: false #hide ultitlities
    core:
      +materialized: table
      +schema: core

    elementary:
      +schema: "elementary"

vars:
    "dbt_date:time_zone": "Asia/Saigon"
    dbt_project_evaluator:
      documentation_coverage_target: 75
      test_coverage_target: 75
      models_fanout_threshold: 10
      model_types: ['base','staging', 'intermediate', 'marts', 'core', 'utils']
      staging_folder_name: staging
      staging_prefixes: ['stg_']
      base_folder_name: base
      base_prefixes: ['base_']
      intermediate_folder_name: intermediate
      intermediate_prefixes: ['int_']
      marts_folder_name: marts
      marts_prefixes: ['','fct_','dim_']
      core_folder_name: core
      core_prefixes: ['']
      utils_folder_name: utilities
      utils_prefixes: ['']

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_project_evaluator', 'dbt']