name: 'sado_analytics_services'
version: '1.0.0'
config-version: 2

require-dbt-version: ">=1.6.0"
profile: 'sado_analytics_services'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"

models:
  sado_analytics_services:
    staging:
      +materialized: view
      base:
        +docs:
          show: false
    intermediate:
      +materialized: ephemeral
      +docs:
        show: false
    marts:
      +materialized: table
      sales:
        +schema: sales
      dimensions:
        +schema: dimensions
      marketing:
        +schema: marketing
      online_sales:
        +schema: online_sales
    utilities:
      +materialized: view
      +docs:
        show: false #hide ultitlities
    core:
      +materialized: table
      +schema: core

vars:
    "dbt_date:time_zone": "Asia/Saigon"