name: "sado_analytics_services"
version: "1.0.0"
config-version: 2

require-dbt-version: ">=1.6.0"
profile: "sado_analytics_services"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sado_analytics_services:
    staging:
      +materialized: view
      caresoft:
        +enabled: false
    intermediate:
      +materialized: ephemeral
      +docs:
        show: false
    marts:
      +materialized: table
      sales:
        +schema: sales
      dimensions:
        +schema: dimensions
      marketing:
        +schema: marketing
      online_sales:
        +schema: online_sales
    utilities:
      +materialized: view
      docs:
        show: false #hide ultitlities
    core:
      +materialized: table
      +schema: core
  ga4:
    staging:
      base:
        base_ga4__events:
          +full_refresh: false
    marts:
      core:
        +schema: marketing

vars:
  "dbt_date.time_zone": "Asia/Saigon"
  ga4:
    source_project: "agile-scheme-394814"
    is_user_id_implemented: false
    property_ids: [336884118,444838415]
    start_date: "20231001"
    static_incremental_days: 1
    query_parameter_exclusions: ["gclid", "fbclid", "_ga"]
    query_parameter_extraction: ["gclid", "fbclid", "keyword"]
    conversion_events: ["purchase", "message", "call", "generate_lead", "store_visit"]
    user_properties:
      - user_property_name: "phone"
        value_type: "string_value"
      - user_property_name: "address"
        value_type: "string_value"
      - user_property_name: "email"
        value_type: "string_value"
      - user_property_name: "name"
        value_type: "string_value"
    derived_user_properties:
      - event_parameter: "page_location"
        user_property_name: "most_recent_page_location"
        value_type: "string_value"
      - event_parameter: "store"
        user_property_name: "visited_branch"
        value_type: "string_value"
      - event_parameter: "location"
        user_property_name: "searched_branch"
        value_type: "string_value"