services:
  app:
    image: sado-analytics-services:latest
    build: .
    container_name: sado-analytics-services
    volumes:
      - ./${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/{GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/{GOOGLE_APPLICATION_CREDENTIALS}
      K_SERVICE: dev
      K_CONFIGURATION: dev
      K_REVISION: dev-00001