sado_analytics_services:
  outputs:
    dev:
      dataset: dbt_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      method: service-account
      priority: interactive
      project: agile-scheme-394814
      threads: 4
      type: bigquery
    prod:
      dataset: dbt_prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      method: service-account
      priority: interactive
      project: agile-scheme-394814
      threads: 4
      type: bigquery
  target: prod
