version: 2
models:
  - name: stg_gsheet__asms
    description: ""
    columns:
      - name: asm_name
        description: ""
        meta:
          dimension:
            type: string
      - name: phone
        description: ""
        meta:
          dimension:
            type: string
      - name: email
        description: ""
        meta:
          dimension:
            type: string
      - name: pic
        description: ""
        meta:
          dimension:
            type: string
      - name: store_name
        description: ""
        meta:
          dimension:
            type: string
      - name: local_page
        description: ""
        meta:
          dimension:
            type: string
      - name: region_page
        description: ""
        meta:
          dimension:
            type: string
      - name: opening_day
        description: ""
        meta:
          dimension:
            type: date
      - name: close_date
        description: ""
        meta:
          dimension:
            type: date
      - name: region
        description: ""
        meta:
          dimension:
            type: string
      - name: province
        description: ""
        meta:
          dimension:
            type: string
  - name: stg_gsheet__facebook_budget
    columns:
      - name: branch
        description: ""
        meta:
          dimension:
            type: string
      - name: budget_month
        description: ""
        meta:
          dimension:
            type: date
      - name: milestones
        description: ""
        meta:
          dimension:
            type: string
  - name: stg_gsheet__pancake_tags
    columns:
      - name: tag_value
        description: ""
        meta:
          dimension:
            type: string
      - name: category
        description: ""
        meta:
          dimension:
            type: string
