WITH source AS (
    {{ dbt_utils.deduplicate(relation = source('pancake', 'posts'), partition_by = 'id,page_id', order_by = "_batched_at desc",) }}
)
SELECT
source.is_dynamic_linked,
source.reactions,
source.like_count,
source.message,
source.delete_comment,
source.privacy,
source.rating_point,
source.type,
source.is_removed,
source.story_tags,
source.comment_count,
source.live_video_ended_time,
source.id as post_id,
source.admin_creator,
source.link,
date_add(source.inserted_at, interval 7 hour) inserted_at,
source.has_running_rules,
source.page_id,
source.recommendation_type,
source.sub_type,
date_add(source.updated_at, interval 7 hour) updated_at,
source.edit_history,
source.dynamic_post_id,
source.from,
source.is_mention,
source.reaction_count,
source.live_video_status,
source.story,
source.share_last_cursor,
source.phone_number_count,
source.status_type,
source.product_id,
source.is_visitor_post,
source.comments_mirroring_domain,
FROM
    source