name: Deploy Docs and Manifest

on:
  push:
  workflow_dispatch:
concurrency: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: |
          pip install dbt-core==1.6.6 dbt-bigquery==1.6.4
          dbt deps
      - id: compile
        run: |
          dbt compile && dbt docs generate
          find ./target -name \*.json -exec cp -v '{}' './prod' ';'
        continue-on-error: true
      - name: Add Manifest to Repo
        uses: EndBug/add-and-commit@v9
        with:
          add: './prod'
          committer_name: Github Actions
          committer_email: actions@github.com
          message: 'Adding manifest from merge run'
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './target'
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
        continue-on-error: true