{{ config(
    tags = ['view','tiktok']
) }}


WITH source AS (

    SELECT
        json_extract_array(data,'$.actions') AS actions,
        json_value(data,'$.adgroup_app_profile_page_state') AS adgroup_app_profile_page_state,
        json_value(data,'$.adgroup_id') AS adgroup_id,
        json_value(data,'$.adgroup_name') AS adgroup_name,
        json_value(data,'$.advertiser_id') AS advertiser_id,
        json_extract_array(data,'$.age_groups') AS age_groups,
        json_value(data,'$.app_download_url') AS app_download_url,
        json_value(data,'$.app_id') AS app_id,
        json_value(data,'$.app_type') AS app_type,
        json_value(data,'$.attribution_event_count') AS attribution_event_count,
        json_extract_array(data,'$.audience_ids') AS audience_ids,
        safe_cast(json_value(data,'$.auto_targeting_enabled') as bool) AS auto_targeting_enabled,
        json_value(data,'$.bid_display_mode') AS bid_display_mode,
        safe_cast(json_value(data,'$.bid_price') as float64) AS bid_price,
        json_value(data,'$.bid_type') AS bid_type,
        json_value(data,'$.billing_event') AS billing_event,
        json_value(data,'$.brand_safety_partner') AS brand_safety_partner,
        json_value(data,'$.brand_safety_type') AS brand_safety_type,
        safe_cast(json_value(data,'$.budget') as float64) AS budget,
        json_value(data,'$.budget_mode') AS budget_mode,
        json_value(data,'$.campaign_id') AS campaign_id,
        json_value(data,'$.campaign_name') AS campaign_name,
        json_value(data,'$.catalog_id') AS catalog_id,
        json_extract_array(data,'$.category_exclusion_ids') AS category_exclusion_ids,
        json_value(data,'$.category_id') AS category_id,
        json_value(data,'$.click_attribution_window') AS click_attribution_window,
        safe_cast(json_value(data,'$.comment_disabled') as bool) AS comment_disabled,
        json_extract_array(data,'$.contextual_tag_ids') AS contextual_tag_ids,
        safe_cast(json_value(data,'$.conversion_bid_price') as float64) AS conversion_bid_price,
        json_value(data,'$.conversion_window') AS conversion_window,
        datetime(json_value(data,'$.create_time')) AS create_time,
        json_value(data,'$.creative_material_mode') AS creative_material_mode,
        json_value(data,'$.dayparting') AS dayparting,
        json_value(data,'$.deep_bid_type') AS deep_bid_type,
        safe_cast(json_value(data,'$.deep_cpa_bid') as float64) AS deep_cpa_bid,
        json_value(data,'$.delivery_mode') AS delivery_mode,
        json_extract_array(data,'$.device_model_ids') AS device_model_ids,
        json_extract_array(data,'$.device_price_ranges') AS device_price_ranges,
        json_extract_array(data,'$.excluded_audience_ids') AS excluded_audience_ids,
        json_extract_array(data,'$.excluded_custom_actions') AS excluded_custom_actions,
        json_value(data,'$.feed_type') AS feed_type,
        json_value(data,'$.frequency') AS frequency,
        json_value(data,'$.frequency_schedule') AS frequency_schedule,
        json_value(data,'$.gender') gender,
        json_value(data,'$.identity_authorized_bc_id') AS identity_authorized_bc_id,
        json_value(data,'$.identity_id') AS identity_id,
        json_value(data,'$.identity_type') AS identity_type,
        json_extract_array(data,'$.included_custom_actions') AS included_custom_actions,
        json_extract_array(data,'$.interest_category_ids') AS interest_category_ids,
        json_extract_array(data,'$.interest_keyword_ids') AS interest_keyword_ids,
        safe_cast(json_value(data,'$.inventory_filter_enabled') as bool) AS inventory_filter_enabled,
        json_value(data,'$.ios14_quota_type') AS ios14_quota_type,
        safe_cast(json_value(data,'$.is_hfss') as bool) AS is_hfss,
        safe_cast(json_value(data,'$.is_new_structure') as bool) AS is_new_structure,
        safe_cast(json_value(data,'$.is_smart_performance_campaign') as bool) AS is_smart_performance_campaign,
        json_extract_array(data,'$.isp_ids') AS isp_ids,
        json_value(data,'$.keywords') AS keywords,
        json_extract_array(data,'$.languages') AS languages,
        json_extract_array(data,'$.location_ids') AS location_ids,
        datetime(json_value(data,'$.modify_time')) AS modify_time,
        json_extract_array(data,'$.network_types') AS network_types,
        json_value(data,'$.next_day_retention') AS next_day_retention,
        json_extract_array(data,'$.operating_systems') AS operating_systems,
        json_value(data,'$.operation_status') AS operation_status,
        json_value(data,'$.optimization_event') AS optimization_event,
        json_value(data,'$.optimization_goal') AS optimization_goal,
        json_value(data,'$.pacing') AS pacing,
        json_value(data,'$.pixel_id') AS pixel_id,
        json_value(data,'$.placement_type') AS placement_type,
        json_extract_array(data,'$.placements') AS placements,
        json_value(data,'$.product_source') AS product_source,
        json_value(data,'$.promotion_type') AS promotion_type,
        json_value(data,'$.purchased_impression') AS purchased_impression,
        json_value(data,'$.purchased_reach') AS purchased_reach,
        json_value(data,'$.rf_estimated_cpr') AS rf_estimated_cpr,
        json_value(data,'$.rf_estimated_frequency') AS rf_estimated_frequency,
        json_value(data,'$.rf_purchased_type') AS rf_purchased_type,
        datetime(json_value(data,'$.schedule_end_time')) AS schedule_end_time,
        json_value(data,'$.schedule_infos') AS schedule_infos,
        datetime(json_value(data,'$.schedule_start_time')) AS schedule_start_time,
        json_value(data,'$.schedule_type') AS schedule_type,
        safe_cast(json_value(data,'$.scheduled_budget') as float64) AS scheduled_budget,
        safe_cast(json_value(data,'$.search_result_enabled') as bool) AS search_result_enabled,
        json_value(data,'$.secondary_optimization_event') AS secondary_optimization_event,
        json_value(data,'$.secondary_status') AS secondary_status,
        safe_cast(json_value(data,'$.share_disabled') as bool) AS share_disabled,
        json_value(data,'$.shopping_ads_type') AS shopping_ads_type,
        safe_cast(json_value(data,'$.skip_learning_phase') as bool) AS skip_learning_phase,
        json_value(data,'$.smart_audience_enabled') AS smart_audience_enabled,
        json_value(data,'$.smart_interest_behavior_enabled') AS smart_interest_behavior_enabled,
        json_value(data,'$.spending_power') AS spending_power,
        json_value(data,'$.statistic_type') AS statistic_type,
        json_value(data,'$.store_authorized_bc_id') AS store_authorized_bc_id,
        json_value(data,'$.store_id') AS store_id,
        safe_cast(json_value(data,'$.video_download_disabled') as bool) AS video_download_disabled,
        json_value(data,'$.view_attribution_window') AS view_attribution_window,
        json_extract_array(data,'$.zipcode_ids') AS zipcode_ids,
    FROM
        {{ source('tiktok','adgroup') }}
) 

{{ dbt_utils.deduplicate(
    relation = "source",
    partition_by = "advertiser_id, campaign_id, adgroup_id",
    order_by = "modify_time desc"
) }}
