{{ config(
    tags = ['view','tiktok']
) }}

WITH source AS (
    SELECT
        json_value(data, '$.info.image_id') AS image_id,
        json_value(data, '$.info.material_id') AS material_id,
        json_value(data, '$.info.page_id') AS page_id,
        json_value(data, '$.info.video_id') AS video_id,
        SAFE_CAST(json_value(data, '$.metrics.add_to_wishlist') AS INT64) AS add_to_wishlist,
        SAFE_CAST(json_value(data, '$.metrics.add_to_wishlist_rate') AS FLOAT64) AS add_to_wishlist_rate,
        SAFE_CAST(json_value(data, '$.metrics.app_event_add_to_cart') AS INT64) AS app_event_add_to_cart,
        SAFE_CAST(json_value(data, '$.metrics.app_event_add_to_cart_rate') AS FLOAT64) AS app_event_add_to_cart_rate,
        SAFE_CAST(json_value(data, '$.metrics.average_video_play') AS FLOAT64) AS average_video_play,
        SAFE_CAST(json_value(data, '$.metrics.checkout') AS INT64) AS checkout,
        SAFE_CAST(json_value(data, '$.metrics.checkout_rate') AS FLOAT64) AS checkout_rate,
        SAFE_CAST(json_value(data, '$.metrics.clicks') AS INT64) AS clicks,
        SAFE_CAST(json_value(data, '$.metrics.complete_payment') AS INT64) AS complete_payment,
        SAFE_CAST(json_value(data, '$.metrics.complete_payment_rate') AS FLOAT64) AS complete_payment_rate,
        SAFE_CAST(json_value(data, '$.metrics.conversion') AS INT64) AS conversion,
        SAFE_CAST(json_value(data, '$.metrics.conversion_rate') AS FLOAT64) AS conversion_rate,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_add_to_wishlist') AS FLOAT64) AS cost_per_add_to_wishlist,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_app_event_add_to_cart') AS FLOAT64) AS cost_per_app_event_add_to_cart,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_checkout') AS FLOAT64) AS cost_per_checkout,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_complete_payment') AS FLOAT64) AS cost_per_complete_payment,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_conversion') AS FLOAT64) AS cost_per_conversion,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_download_start') AS FLOAT64) AS cost_per_download_start,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_initiate_checkout') AS FLOAT64) AS cost_per_initiate_checkout,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_page_event_search') AS FLOAT64) AS cost_per_page_event_search,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_product_details_page_browse') AS FLOAT64) AS cost_per_product_details_page_browse,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_purchase') AS FLOAT64) AS cost_per_purchase,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_registration') AS FLOAT64) AS cost_per_registration,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_total_add_to_wishlist') AS FLOAT64) AS cost_per_total_add_to_wishlist,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_total_app_event_add_to_cart') AS FLOAT64) AS cost_per_total_app_event_add_to_cart,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_total_checkout') AS FLOAT64) AS cost_per_total_checkout,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_total_purchase') AS FLOAT64) AS cost_per_total_purchase,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_total_registration') AS FLOAT64) AS cost_per_total_registration,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_total_view_content') AS FLOAT64) AS cost_per_total_view_content,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_user_registration') AS FLOAT64) AS cost_per_user_registration,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_view_content') AS FLOAT64) AS cost_per_view_content,
        SAFE_CAST(json_value(data, '$.metrics.cost_per_web_event_add_to_cart') AS FLOAT64) AS cost_per_web_event_add_to_cart,
        SAFE_CAST(json_value(data, '$.metrics.cpc') AS FLOAT64) AS cpc,
        SAFE_CAST(json_value(data, '$.metrics.cpm') AS FLOAT64) AS cpm,
        SAFE_CAST(json_value(data, '$.metrics.ctr') AS FLOAT64) AS ctr,
        SAFE_CAST(json_value(data, '$.metrics.download_start_rate') AS FLOAT64) AS download_start_rate,
        SAFE_CAST(json_value(data, '$.metrics.impressions') AS INT64) AS impressions,
        SAFE_CAST(json_value(data, '$.metrics.initiate_checkout') AS INT64) AS initiate_checkout,
        SAFE_CAST(json_value(data, '$.metrics.initiate_checkout_rate') AS FLOAT64) AS initiate_checkout_rate,
        SAFE_CAST(json_value(data, '$.metrics.page_event_search') AS INT64) AS page_event_search,
        SAFE_CAST(json_value(data, '$.metrics.page_event_search_rate') AS FLOAT64) AS page_event_search_rate,
        SAFE_CAST(json_value(data, '$.metrics.product_details_page_browse') AS INT64) AS product_details_page_browse,
        SAFE_CAST(json_value(data, '$.metrics.product_details_page_browse_rate') AS FLOAT64) AS product_details_page_browse_rate,
        SAFE_CAST(json_value(data, '$.metrics.purchase') AS INT64) AS purchase,
        SAFE_CAST(json_value(data, '$.metrics.purchase_rate') AS FLOAT64) AS purchase_rate,
        SAFE_CAST(json_value(data, '$.metrics.registration') AS INT64) AS registration,
        SAFE_CAST(json_value(data, '$.metrics.registration_rate') AS FLOAT64) AS registration_rate,
        SAFE_CAST(json_value(data, '$.metrics.sales_lead') AS INT64) AS sales_lead,
        SAFE_CAST(json_value(data, '$.metrics.spend') AS FLOAT64) AS spend,
        SAFE_CAST(json_value(data, '$.metrics.total_add_to_wishlist') AS INT64) AS total_add_to_wishlist,
        SAFE_CAST(json_value(data, '$.metrics.total_add_to_wishlist_value') AS FLOAT64) AS total_add_to_wishlist_value,
        SAFE_CAST(json_value(data, '$.metrics.total_app_event_add_to_cart') AS INT64) AS total_app_event_add_to_cart,
        SAFE_CAST(json_value(data, '$.metrics.total_app_event_add_to_cart_value') AS FLOAT64) AS total_app_event_add_to_cart_value,
        SAFE_CAST(json_value(data, '$.metrics.total_checkout') AS INT64) AS total_checkout,
        SAFE_CAST(json_value(data, '$.metrics.total_checkout_value') AS FLOAT64) AS total_checkout_value,
        SAFE_CAST(json_value(data, '$.metrics.total_complete_payment_rate') AS FLOAT64) AS total_complete_payment_rate,
        SAFE_CAST(json_value(data, '$.metrics.total_download_start_value') AS FLOAT64) AS total_download_start_value,
        SAFE_CAST(json_value(data, '$.metrics.total_initiate_checkout_value') AS FLOAT64) AS total_initiate_checkout_value,
        SAFE_CAST(json_value(data, '$.metrics.total_page_event_search_value') AS FLOAT64) AS total_page_event_search_value,
        SAFE_CAST(json_value(data, '$.metrics.total_product_details_page_browse_value') AS FLOAT64) AS total_product_details_page_browse_value,
        SAFE_CAST(json_value(data, '$.metrics.total_purchase') AS INT64) AS total_purchase,
        SAFE_CAST(json_value(data, '$.metrics.total_purchase_value') AS FLOAT64) AS total_purchase_value,
        SAFE_CAST(json_value(data, '$.metrics.total_registration') AS INT64) AS total_registration,
        SAFE_CAST(json_value(data, '$.metrics.total_sales_lead') AS INT64) AS total_sales_lead,
        SAFE_CAST(json_value(data, '$.metrics.total_sales_lead_value') AS FLOAT64) AS total_sales_lead_value,
        SAFE_CAST(json_value(data, '$.metrics.total_user_registration_value') AS FLOAT64) AS total_user_registration_value,
        SAFE_CAST(json_value(data, '$.metrics.total_view_content') AS INT64) AS total_view_content,
        SAFE_CAST(json_value(data, '$.metrics.total_view_content_value') AS FLOAT64) AS total_view_content_value,
        SAFE_CAST(json_value(data, '$.metrics.total_web_event_add_to_cart_value') AS FLOAT64) AS total_web_event_add_to_cart_value,
        SAFE_CAST(json_value(data, '$.metrics.user_registration') AS INT64) AS user_registration,
        SAFE_CAST(json_value(data, '$.metrics.user_registration_rate') AS FLOAT64) AS user_registration_rate,
        SAFE_CAST(json_value(data, '$.metrics.value_per_checkout') AS FLOAT64) AS value_per_checkout,
        SAFE_CAST(json_value(data, '$.metrics.value_per_complete_payment') AS FLOAT64) AS value_per_complete_payment,
        SAFE_CAST(json_value(data, '$.metrics.value_per_download_start') AS FLOAT64) AS value_per_download_start,
        SAFE_CAST(json_value(data, '$.metrics.value_per_initiate_checkout') AS FLOAT64) AS value_per_initiate_checkout,
        SAFE_CAST(json_value(data, '$.metrics.value_per_page_event_search') AS FLOAT64) AS value_per_page_event_search,
        SAFE_CAST(json_value(data, '$.metrics.value_per_product_details_page_browse') AS FLOAT64) AS value_per_product_details_page_browse,
        SAFE_CAST(json_value(data, '$.metrics.value_per_total_add_to_wishlist') AS FLOAT64) AS value_per_total_add_to_wishlist,
        SAFE_CAST(json_value(data, '$.metrics.value_per_total_app_event_add_to_cart') AS FLOAT64) AS value_per_total_app_event_add_to_cart,
        SAFE_CAST(json_value(data, '$.metrics.value_per_total_purchase') AS FLOAT64) AS value_per_total_purchase,
        SAFE_CAST(json_value(data, '$.metrics.value_per_total_view_content') AS FLOAT64) AS value_per_total_view_content,
        SAFE_CAST(json_value(data, '$.metrics.value_per_user_registration') AS FLOAT64) AS value_per_user_registration,
        SAFE_CAST(json_value(data, '$.metrics.value_per_web_event_add_to_cart') AS FLOAT64) AS value_per_web_event_add_to_cart,
        SAFE_CAST(json_value(data, '$.metrics.video_play_actions') AS INT64) AS video_play_actions,
        SAFE_CAST(json_value(data, '$.metrics.video_views_p100') AS INT64) AS video_views_p100,
        SAFE_CAST(json_value(data, '$.metrics.video_views_p25') AS INT64) AS video_views_p25,
        SAFE_CAST(json_value(data, '$.metrics.video_views_p50') AS INT64) AS video_views_p50,
        SAFE_CAST(json_value(data, '$.metrics.video_views_p75') AS INT64) AS video_views_p75,
        SAFE_CAST(json_value(data, '$.metrics.video_watched_2s') AS INT64) AS video_watched_2s,
        SAFE_CAST(json_value(data, '$.metrics.video_watched_6s') AS INT64) AS video_watched_6s,
        SAFE_CAST(json_value(data, '$.metrics.view_content') AS INT64) AS view_content,
        SAFE_CAST(json_value(data, '$.metrics.view_content_rate') AS FLOAT64) AS view_content_rate,
        SAFE_CAST(json_value(data, '$.metrics.web_event_add_to_cart') AS INT64) AS web_event_add_to_cart,
        SAFE_CAST(json_value(data, '$.metrics.web_event_add_to_cart_rate') AS FLOAT64) AS web_event_add_to_cart_rate,
        _batched_at
    FROM
        {{source('tiktok','creative_report')}}

) 

{{ dbt_utils.deduplicate(
    relation = "source",
    partition_by = "material_id",
    order_by = "_batched_at desc"
) }}
